# Get contacts
GET http://localhost:4000/api/contacts

###
# Info
GET http://localhost:4000/info

###
# Get contact
GET http://localhost:4000/api/contacts/3

###
# Delete contact
DELETE http://localhost:4000/api/contacts/3

###
# Create contact
POST http://localhost:4000/api/contacts
Content-Type: application/json

{
  "name": "Pedro Pablo",
  "phone": "123456789"
}