# Get blogs
GET http://localhost:4000/api/blogs

###
# Create blog
POST http://localhost:4000/api/blogs
Content-Type: application/json

{
  "title": "My first blog",
  "author": "Carlos Acosta",
  "url": "www.example.com",
  "likes": 10,
  "userId": "6a720cfb227ffb5d3e5cde30"
}
