@baseUrl = http://localhost:4000

# Get blogs
GET {{baseUrl}}/api/blogs

###
# Create blog
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
  "title": "My first blog",
  "author": "Carlos Acosta",
  "url": "www.example.com",
  "likes": 10,
  "userId": "6a720cfb227ffb5d3e5cde30"
}

###
# Delete blog
DELETE {{baseUrl}}/api/blogs/6a720d1b227ffb5d3e5cde31
Authorization: `Bearer ${eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik90aXM5OSIsImlkIjoiNmE3Mjg5Y2U2OGExYWFjN2NjZTkxM2I0IiwiaWF0IjoxNzg1OTY5ODMyLCJleHAiOjE3ODU5NzM0MzJ9.S858F0P-Ysnj6OUEybjd2W4UPwdergal1JIH24IlfvY}`