@baseUrl = http://localhost:4000

# Create user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
   "name": "Pedro",
   "username": "bubloy",
   "password": "pa"
}

###
# Get users
GET {{baseUrl}}/api/users
