@baseUrl = http://localhost:4000

# Get users
GET {{baseUrl}}/api/users

###
# Create user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "username": "juski10",
  "name": "Andres Hoyos",
  "password": "password"
}
